---
- name: Setup project environment
  hosts: localhost

  vars_files:
    - ../main.vars.yml

  tasks:
    - name: gather information about Ubuntu 22.04 AMIs published by Canonical (099720109477)
      amazon.aws.ec2_ami_info:
        owners: 099720109477
        filters:
          name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
      register: ubuntu_amis

    - set_fact:
        first_ubuntu_ami: "{{ ubuntu_amis.images | first }}"

    - set_fact:
        ubuntu_ami_id: "{{ first_ubuntu_ami.image_id }}"

    - debug:
        var: ubuntu_ami_id

    - name: Upload SSH key to AWS EC2
      amazon.aws.ec2_key:
        name: "{{ key_name }}"  # The name for the key pair in AWS
        key_material: "{{ lookup('file', local_key_path) }}"  # The local SSH private key file
        region: "{{ aws_region }}"  # AWS region where the EC2 instances will be created
        tags:
          project: "{{ project_name }}"

    - name: start instance a with a public IP address
      amazon.aws.ec2_instance:
        name: "instance-a"
        instance_type: t2.micro
        key_name: "{{ key_name }}"
        image_id: "{{ ubuntu_ami_id }}"
        region: "{{ aws_region }}"
        network_interfaces:
          - assign_public_ip: true
        tags:
          project: "{{ project_name }}"

    - name: start instance b with a public IP address
      amazon.aws.ec2_instance:
        name: "instance-b"
        instance_type: t2.micro
        key_name: "{{ key_name }}"
        image_id: "{{ ubuntu_ami_id }}"
        region: "{{ aws_region }}"
        network_interfaces:
          - assign_public_ip: true
        tags:
          project: "{{ project_name }}"
