---
- name: Teardown project environment
  hosts: localhost

  vars_files:
    - ../main.vars.yml

  tasks:
    - name: Destroy instance a
      amazon.aws.ec2_instance:
        name: "instance-a"
        state: absent

    - name: Destroy instance b
      amazon.aws.ec2_instance:
        name: "instance-b"
        state: absent

    - name: Remove ec2 ssh key
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: absent

    - name: Remove security group
      amazon.aws.ec2_group:
        name: "local-ssh-demo-access"
        region: "{{ aws_region }}"
        state: absent

    - name: Remove security group
      amazon.aws.ec2_group:
        name: "instance-connectivity-inbound"
        region: "{{ aws_region }}"
        state: absent

    - name: Remove security group
      amazon.aws.ec2_group:
        name: "instance-connectivity-outbound"
        region: "{{ aws_region }}"
        state: absent
