---

- name: Setup metal device networking
  hosts:
    - instance-a
    - instance-b

  vars_files:
    - main.vars.yml


  tasks:
    - name: Create VLAN for internal traffic
      equinix.cloud.metal_vlan:
        description: "internal"
        project_id: "{{ project_id }}"
        metro: "sy"
        vxlan: "{{ internal_vxlan_id }}"
      register: vlan_a
      delegate_to: localhost

    - name: Get info on devices metal ports
      set_fact:
        bond_port_id: "{{ hostvars[inventory_hostname].network_ports | selectattr('name', 'match', 'bond0') | map(attribute='id') | first }}"

    - name: Add vlans to bond port in hybrid bonded mode
      equinix.cloud.metal_port:
        id: "{{ bond_port_id  }}"
        bonded: true
        layer2: false
        vlan_ids:
          - "{{ vlan_a.id }}"
      delegate_to: localhost

    - name: Make sure the vlan package is installed
      ansible.builtin.apt:
        name: vlan
        state: present

    - name: Add the 802.1q module for vlans
      community.general.modprobe:
        name: 8021q
        state: present

    - name: Update interfaces for internal vlan network
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto bond0.{{ internal_vxlan_id }}
          iface bond0.{{ internal_vxlan_id }} inet static
            pre-up sleep 5
            address {{ private_address[inventory_hostname] }}/24
            netmask 255.255.255.0
            vlan-raw-device bond0

    - name: Restart networking to apply changes
      ansible.builtin.service:
        name: networking
        state: restarted
