---

- name: Modifying metal device networking
  hosts:
    - instance-a
    - instance-b

  vars_files:
    - ../main.vars.yml

  tasks:
    - name: Get info on devices metal ports
      set_fact:
        bond_port_id: "{{ hostvars[inventory_hostname].network_ports | selectattr('name', 'match', 'bond0') | map(attribute='id') | first }}"

    - name: Revert bonded port back to defaults
      equinix.cloud.metal_port:
        id: "{{ bond_port_id  }}"
        bonded: true
      delegate_to: localhost

    - name: Remove networking blog from interfaces file
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto bond0.{{ internal_vxlan_id }}
          iface bond0.{{ internal_vxlan_id }} inet static
            pre-up sleep 5
            address {{ private_address[inventory_hostname] }}/24
            netmask 255.255.255.0
            vlan-raw-device bond0
        state: absent

    - name: Restart networking service on host to apply changes
      ansible.builtin.service:
        name: networking
        state: restarted
